name: Bug report
description: Report a reproducible bug in kinship.
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
        Please provide enough detail for maintainers to reproduce and verify the issue.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: A clear and concise summary of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal, deterministic steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: repro_data
    attributes:
      label: Minimal pedigree input/sample
      description: Provide a small synthetic dataset or snippet that reproduces the issue.
      render: typescript
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/errors
      description: Stack traces, validation diagnostics, or console output.
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version/commit
      description: Library version, tag, or commit SHA where the issue appears.
      placeholder: v0.x.x or commit SHA
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Runtime and OS information.
      placeholder: Bun x.y.z / Node x.y.z, macOS/Linux/Windows
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I used synthetic data only (no real personal/private dataset).
          required: true
        - label: I agree to follow this project's Code of Conduct.
          required: true
